version: '3.7'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BUILD_APP: app
    command: >
      sh -c 'npm i && npm run build && npm run start'
    ports:
      - '${APP_OUT_PORT}:${APP_PORT}'
    volumes:
      - .:/app/
      - /app/node_modules/
      - /app/dist/
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0-alpine3.14
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - '${DB_OUT_PORT}:${DB_PORT}'

volumes:
  database:
    driver: 'local'
