version: '3.7'

services:
  postgres:
    image: postgres:14.0-alpine3.14
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - '${DB_OUT_PORT}:${DB_PORT}'

volumes:
  database:
    driver: 'local'